const ROV_BASE   = '/images/ALASKAN_WEB_ASSET/PACKAGE ICON/ROV';
const FF_BASE    = '/images/ALASKAN_WEB_ASSET/PACKAGE ICON/FREEFIRE';
const PUBGM_BASE = '/images/ALASKAN_WEB_ASSET/PACKAGE ICON/PUBGM';
const MLBB_BASE  = '/images/ALASKAN_WEB_ASSET/PACKAGE ICON/MLBB';

const MLBB_PKG = (server, country) => [
  { id: `mlbb-${server}-ltv`,  amount: 0,    label: 'Limited-Time Value Pack', price: 9,    img: `${MLBB_BASE}/mlbb_LimitedTimeValuePack.png` },
  { id: `mlbb-${server}-web`,  amount: 0,    label: 'Weekly Elite Bundle',     price: 27,   img: `${MLBB_BASE}/Weekly Elite Bundle_mlbb.png` },
  { id: `mlbb-${server}-55`,   amount: 55,   price: 29,                                     img: `${MLBB_BASE}/mlbb_diamond1.png` },
  { id: `mlbb-${server}-86`,   amount: 78,   bonus: '+8',                      price: 41,   img: `${MLBB_BASE}/mlbb_diamond1.png` },
  { id: `mlbb-${server}-wdp`,  amount: 0,    label: 'Weekly Diamond Pass',     price: 55,   img: `${MLBB_BASE}/mlbb_WeeklyDiamondPass.png` },
  { id: `mlbb-${server}-165`,  amount: 165,  price: 81,                                     img: `${MLBB_BASE}/mlbb_diamond2.png` },
  { id: `mlbb-${server}-172`,  amount: 156,  bonus: '+16',                     price: 83,   img: `${MLBB_BASE}/mlbb_diamond2.png` },
  { id: `mlbb-${server}-257`,  amount: 234,  bonus: '+23',                     price: 119,  badge: 'แนะนำ', img: `${MLBB_BASE}/mlbb_diamond3.png` },
  { id: `mlbb-${server}-275`,  amount: 275,  price: 125,                                    img: `${MLBB_BASE}/mlbb_diamond3.png` },
  { id: `mlbb-${server}-meb`,  amount: 0,    label: 'Monthly Epic Bundle',     price: 129,  img: `${MLBB_BASE}/Monthly Epic Bundle_mlbb.png` },
  { id: `mlbb-${server}-565`,  amount: 565,  price: 259,                                    img: `${MLBB_BASE}/mlbb_diamond4.png` },
  { id: `mlbb-${server}-twp`,  amount: 0,    label: 'Twilight Pass',           price: 265,  img: `${MLBB_BASE}/mlbb_TwilightPass.png` },
  { id: `mlbb-${server}-706`,  amount: 625,  bonus: '+81',                     price: 315,  badge: 'ขายดี', img: `${MLBB_BASE}/mlbb_diamond5.png` },
  { id: `mlbb-${server}-2195`, amount: 1860, bonus: '+335',                    price: 945,  img: `${MLBB_BASE}/mlbb_diamond6.png` },
  { id: `mlbb-${server}-3688`, amount: 3099, bonus: '+589',                    price: 1575, img: `${MLBB_BASE}/mlbb_diamond7.png` },
  { id: `mlbb-${server}-5532`, amount: 4649, bonus: '+883',                    price: 2370, img: `${MLBB_BASE}/mlbb_diamond8.png` },
  { id: `mlbb-${server}-9288`, amount: 7740, bonus: '+1548',                   price: 3920, img: `${MLBB_BASE}/mlbb_diamond9.png` },
].map(pkg => ({ ...pkg, country }));

const MLBB_SHARED = {
  name: 'Mobile Legends',
  icon: '/images/ALASKAN_WEB_ASSET/GAMES ICON/MOBILE LEGENDS/MOBILE LEGENDS.png',
  bg: '/images/ALASKAN_WEB_ASSET/BACKGROUND/background_web_Alaskan/game_banner/edit/mobilelegends_web_banner.png',
  category: 'เกม MOBA',
  currency: 'เพชร',
  showOnHome: true,
  tags: ['โปรโมชั่น', 'ขายดี'],
  accountFields: [
    { key: 'userId',   label: 'User ID',   placeholder: 'เช่น 123456789', inputMode: 'numeric', required: true },
    { key: 'serverId', label: 'Server ID', placeholder: 'เช่น 1234',      inputMode: 'numeric', required: true },
  ],
  accountHint: 'Mobile Legends ต้องใช้ทั้ง User ID และ Server ID ตรวจสอบให้ถูกต้องก่อนยืนยัน',
};

export const GAMES = {

  // ══════════════════════════════════════════
  //  เกม MOBA
  // ══════════════════════════════════════════

  ROV: {
    id: 'ROV',
    name: 'ROV',
    subtitle: 'Realm of Valor — เติมคูปอง',
    icon: '/images/GAMES ICON/ROV_iconapp.png',
    bg: '/images/GAMES BG/ROV_bg.png',
    promoBg: '/images/BG_UID/ROV.png',
    promoAspect: '21 / 7',
    howtoImage: '/images/HOW%20TO/H_ROV.jpg',
    category: 'เกม MOBA',
    currency: 'คูปอง',
    tag: 'ขายดี',
    showOnHome: true,
    tags: ['โปรโมชั่น', 'ขายดี'],
    info: {
      title: 'บริการเติมคูปอง ROV',
      taglines: [
        'ALASKAN SHOP ตัวแทนจำหน่ายและผู้ให้บริการเติมคูปองเกม ROV ในราคาคุ้มค่าสุดๆ',
        'สะดวก รวดเร็ว ปลอดภัย ถูกต้องตามระบบที่ตัวเกมกำหนดแน่นอน 100%',
      ],
      sections: [
        {
          heading: 'เติม ROV กับ ALASKAN SHOP ดีกว่าเติมเองในเกมยังไง?',
          ordered: false,
          items: [
            'คุ้มและประหยัดกว่าเติมเองในเกม',
            'สะดวก รวดเร็ว พร้อมให้บริการตลอด 24 ช.ม.',
            'ง่าย ไม่ยุ่งยาก ใช้แค่ OPEN ID คัดลอกจากในเกมได้เลย',
          ],
        },
        {
          heading: 'ขั้นตอนการใช้บริการเติม ROV',
          ordered: true,
          items: [
            'คัดลอก OPEN ID มาใส่ในช่องที่กำหนด',
            'เลือกแพ็กเกจที่ต้องการเติม',
            'กดปุ่ม "ถัดไป" และยืนยันออเดอร์',
            'เลือกช่องทางชำระเงินที่ต้องการ',
            'ดำเนินการชำระเงิน รอรับของในเกมได้เลย!!',
          ],
        },
      ],
    },
    packages: [
      { id: 1,  amount: 10,    price: 10,   bonus: '+1',   img: `${ROV_BASE}/rov_coupon1.png` },
      { id: 2,  amount: 20,    price: 19,   bonus: '+4',   img: `${ROV_BASE}/rov_coupon1.png` },
      { id: 3,  amount: 30,    price: 29,   bonus: '+3',   img: `${ROV_BASE}/rov_coupon1.png` },
      { id: 4,  amount: 40,    price: 39,   bonus: '+8',   badge: 'แนะนำ', img: `${ROV_BASE}/rov_coupon2.png` },
      { id: 5,  amount: 50,    price: 48,   bonus: '+10',  img: `${ROV_BASE}/rov_coupon2.png` },
      { id: 6,  amount: 60,    price: 72,   bonus: '+12',  img: `${ROV_BASE}/rov_coupon2.png` },
      { id: 7,  amount: 83,    price: 88,   bonus: '+27',  img: `${ROV_BASE}/rov_coupon3.png` },
      { id: 8,  amount: 100,   price: 98,   bonus: '+20',  img: `${ROV_BASE}/rov_coupon3.png` },
      { id: 9,  amount: 125,   price: 144,  bonus: '+60',  img: `${ROV_BASE}/rov_coupon3.png` },
      { id: 10, amount: 166,   price: 176,  bonus: '+54',  img: `${ROV_BASE}/rov_coupon4.png` },
      { id: 11, amount: 249,   price: 265,  bonus: '+81',  img: `${ROV_BASE}/rov_coupon4.png` },
      { id: 12, amount: 333,   price: 288,  bonus: '+37',  img: `${ROV_BASE}/rov_coupon4.png` },
      { id: 13, amount: 332,   price: 354,  bonus: '+108', img: `${ROV_BASE}/rov_coupon5.png` },
      { id: 14, amount: 375,   price: 434,  bonus: '+180', badge: 'ขายดี', img: `${ROV_BASE}/rov_coupon5.png` },
      { id: 15, amount: 590,   price: 480,  bonus: '+30',  img: `${ROV_BASE}/rov_coupon5.png` },
      { id: 16, amount: 666,   price: 579,  bonus: '+74',  img: `${ROV_BASE}/rov_coupon6.png` },
      { id: 17, amount: 625,   price: 725,  bonus: '+300', img: `${ROV_BASE}/rov_coupon6.png` },
      { id: 18, amount: 999,   price: 869,  bonus: '+111', img: `${ROV_BASE}/rov_coupon6.png` },
      { id: 19, amount: 1178,  price: 950,  bonus: '+62',  img: `${ROV_BASE}/rov_coupon7.png` },
      { id: 20, amount: 1332,  price: 1150, bonus: '+148', img: `${ROV_BASE}/rov_coupon7.png` },
      { id: 21, amount: 1770,  price: 1860, bonus: '+90',  img: `${ROV_BASE}/rov_coupon7.png` },
      { id: 22, amount: 2356,  price: 1900, bonus: '+124', img: `${ROV_BASE}/rov_coupon8.png` },
      { id: 23, amount: 3534,  price: 2850, bonus: '+186', img: `${ROV_BASE}/rov_coupon8.png` },
      { id: 24, amount: 4712,  price: 3800, bonus: '+248', img: `${ROV_BASE}/rov_coupon8.png` },
      { id: 25, amount: 5890,  price: 4750, bonus: '+310', img: `${ROV_BASE}/rov_coupon9.png` },
      { id: 26, amount: 7068,  price: 5700, bonus: '+372', img: `${ROV_BASE}/rov_coupon9.png` },
      { id: 27, amount: 8246,  price: 6650, bonus: '+434', img: `${ROV_BASE}/rov_coupon9.png` },
      { id: 28, amount: 9424,  price: 7600, bonus: '+496', img: `${ROV_BASE}/rov_coupon9.png` },
      { id: 29, amount: 10602, price: 8550, bonus: '+558', img: `${ROV_BASE}/rov_coupon9.png` },
      { id: 30, amount: 11780, price: 9500, bonus: '+620', img: `${ROV_BASE}/rov_coupon9.png` },
    ],
  },

  // ── Mobile Legends ─────────────────────────────────────────────────────────
  'Mobile Legends': { ...MLBB_SHARED, id: 'Mobile Legends', subtitle: 'Mobile Legends — Global', tag: null, country: 'thailand', tags: ['ขายดี'], packages: MLBB_PKG('th', 'thailand') },
  // 'Mobile Legends ID': { ...MLBB_SHARED, id: 'Mobile Legends ID', subtitle: 'Mobile Legends — Server อินโดนีเซีย', tag: 'ขายดี',  country: 'indonesia',                tags: [], packages: MLBB_PKG('id', 'indonesia') },
  // 'Mobile Legends MY': { ...MLBB_SHARED, id: 'Mobile Legends MY', subtitle: 'Mobile Legends — Server มาเลเซีย',   tag: null,     country: 'malaysia',                 tags: [], packages: MLBB_PKG('my', 'malaysia') },
  // 'Mobile Legends PH': { ...MLBB_SHARED, id: 'Mobile Legends PH', subtitle: 'Mobile Legends — Server ฟิลิปปินส์',tag: null,     country: 'philippines',              tags: [], packages: MLBB_PKG('ph', 'philippines') },
  // 'Mobile Legends SG': { ...MLBB_SHARED, id: 'Mobile Legends SG', subtitle: 'Mobile Legends — Server สิงคโปร์',  tag: null,     country: 'singapore',                tags: [], packages: MLBB_PKG('sg', 'singapore') },
  // 'Mobile Legends RU': { ...MLBB_SHARED, id: 'Mobile Legends RU', subtitle: 'Mobile Legends — Server รัสเซีย',   tag: null,     country: 'russia',                   tags: [], packages: MLBB_PKG('ru', 'russia') },
  // 'Mobile Legends TR': { ...MLBB_SHARED, id: 'Mobile Legends TR', subtitle: 'Mobile Legends — Server ตุรกี',     tag: null,     country: 'turkey',                   tags: [], packages: MLBB_PKG('tr', 'turkey') },
  // 'Mobile Legends US': { ...MLBB_SHARED, id: 'Mobile Legends US', subtitle: 'Mobile Legends — Server สหรัฐฯ',   tag: null,     country: 'united-states-of-america', tags: [], packages: MLBB_PKG('us', 'united-states-of-america') },

  'Honor of Kings': {
    id: 'Honor of Kings',
    name: 'Honor of Kings',
    subtitle: 'Honor of Kings — เติมโทเค็น',
    icon: '/images/GAMES ICON/HONOROFKINGS_iconapp.png',
    bg: '/images/GAMES BG/HONOROFKINGS_bg.png',
    category: 'เกม MOBA',
    currency: 'โทเค็น',
    tag: null,
    showOnHome: true,
    packages: [
      { id: 'hok-16',   amount: 16,   price: 7,    img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HONOR%20OF%20KING/honorofking_coupon.png' },
      { id: 'hok-80',   amount: 80,   price: 30,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HONOR%20OF%20KING/honorofking_coupon.png' },
      { id: 'hok-wc',   amount: 0,    label: 'Weekly Card',      price: 32,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HONOR%20OF%20KING/honorofking_WeeklyCard.png' },
      { id: 'hok-240',  amount: 240,  price: 89,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HONOR%20OF%20KING/honorofking_coupon.png' },
      { id: 'hok-wcp',  amount: 0,    label: 'Weekly Card Plus', price: 99,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HONOR%20OF%20KING/honorofking_WeeklyCardPlus.png' },
      { id: 'hok-400',  amount: 400,  price: 147,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HONOR%20OF%20KING/honorofking_coupon.png' },
      { id: 'hok-560',  amount: 560,  price: 207,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HONOR%20OF%20KING/honorofking_coupon.png' },
      { id: 'hok-830',  amount: 800,  bonus: '+30',  price: 295,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HONOR%20OF%20KING/honorofking_coupon.png' },
      { id: 'hok-1245', amount: 1200, bonus: '+45',  price: 443,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HONOR%20OF%20KING/honorofking_coupon.png' },
      { id: 'hok-2508', amount: 2400, bonus: '+108', price: 886,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HONOR%20OF%20KING/honorofking_coupon.png' },
      { id: 'hok-4180', amount: 4000, bonus: '+180', price: 1477, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HONOR%20OF%20KING/honorofking_coupon.png' },
      { id: 'hok-8360', amount: 8000, bonus: '+360', price: 2927, badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HONOR%20OF%20KING/honorofking_coupon.png' },
    ],
  },

  'LoL: Wild Rift': {
    id: 'LoL: Wild Rift',
    name: 'LoL: Wild Rift',
    subtitle: 'League of Legends: Wild Rift — เติม Wild Cores',
    icon: '/images/GAMES ICON/LOLWILDRIFT_iconapp.png',
    bg: '/images/GAMES BG/LOLWILDRIFT_bg.png',
    category: 'เกม MOBA',
    currency: 'Wild Cores',
    tag: null,
    showOnHome: true,
    accountFields: [
      { key: 'riotId', label: 'Riot ID', placeholder: 'กรุณากรอก Riot ID (แบบมี#หลังชื่อด้วย)', required: true },
    ],
    accountHint: 'Riot ID มีรูปแบบ ชื่อ#TAG เช่น CoolPlayer#TH1',
    packages: [
      { id: 'lolwr-425',   amount: 425,   price: 145,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/LoLWR_cores.png' },
      { id: 'lolwr-1000',  amount: 1000,  price: 329,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/LoLWR_cores.png' },
      { id: 'lolwr-1850',  amount: 1850,  price: 579,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/LoLWR_cores.png' },
      { id: 'lolwr-3275',  amount: 3275,  price: 1010, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/LoLWR_cores.png' },
      { id: 'lolwr-4800',  amount: 4800,  price: 1440, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/LoLWR_cores.png' },
      { id: 'lolwr-10000', amount: 10000, price: 2880, badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/LoLWR_cores.png' },
    ],
  },

  'League of Legends': {
    id: 'League of Legends',
    name: 'League of Legends',
    subtitle: 'League of Legends — เติม Crystal',
    icon: '/images/GAMES ICON/LOL_iconapp.png',
    bg: '/images/GAMES BG/LOL_bg.png',
    category: 'เกม MOBA',
    currency: 'Crystal',
    tag: null,
    showOnHome: true,
    accountFields: [
      { key: 'riotId', label: 'Riot ID', placeholder: 'กรุณากรอก Riot ID (แบบมี#หลังชื่อด้วย)', required: true },
    ],
    accountHint: 'Riot ID มีรูปแบบ ชื่อ#TAG เช่น CoolPlayer#TH1',
    packages: [
      { id: 'lol-575',   amount: 575,   price: 126,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/LoL_RP.png' },
      { id: 'lol-1380',  amount: 1380,  price: 283,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/LoL_RP.png' },
      { id: 'lol-2800',  amount: 2800,  price: 538,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/LoL_RP.png' },
      { id: 'lol-4500',  amount: 4500,  price: 855,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/LoL_RP.png' },
      { id: 'lol-6500',  amount: 6500,  price: 1200, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/LoL_RP.png' },
      { id: 'lol-13500', amount: 13500, price: 2450, badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/LoL_RP.png' },
    ],
  },

  'Magic Chess': {
    id: 'Magic Chess',
    name: 'Magic Chess',
    subtitle: 'Magic Chess: Bang Bang — เติมเพชร',
    icon: '/images/GAMES ICON/MAGICCHESS_iconapp.png',
    bg: '/images/GAMES BG/MAGICCHESS_bg.png',
    category: 'เกม MOBA',
    currency: 'เพชร',
    tag: null,
    showOnHome: true,
    packages: [
      { id: 'mc-5',    amount: 5,    price: 5,    img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/magicchess_dimonds.png' },
      { id: 'mc-11',   amount: 10,   bonus: '+1',   price: 8,    img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/magicchess_dimonds.png' },
      { id: 'mc-22',   amount: 20,   bonus: '+2',   price: 12,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/magicchess_dimonds.png' },
      { id: 'mc-56',   amount: 51,   bonus: '+5',   price: 28,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/magicchess_dimonds.png' },
      { id: 'mc-112',  amount: 102,  bonus: '+10',  price: 55,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/magicchess_dimonds.png' },
      { id: 'mc-223',  amount: 203,  bonus: '+20',  price: 105,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/magicchess_dimonds.png' },
      { id: 'mc-336',  amount: 303,  bonus: '+33',  price: 159,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/magicchess_dimonds.png' },
      { id: 'mc-570',  amount: 504,  bonus: '+66',  price: 261,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/magicchess_dimonds.png' },
      { id: 'mc-1163', amount: 1007, bonus: '+156', price: 520,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/magicchess_dimonds.png' },
      { id: 'mc-2398', amount: 2015, bonus: '+383', price: 1040, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/magicchess_dimonds.png' },
      { id: 'mc-6042', amount: 5035, bonus: '+1007',price: 2600, badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/magicchess_dimonds.png' },
    ],
  },

  // ══════════════════════════════════════════
  //  เกม Battle Royale
  // ══════════════════════════════════════════

  'Free Fire': {
    id: 'Free Fire',
    name: 'Free Fire',
    subtitle: 'Garena Free Fire — เติมเพชร & พาส',
    icon: '/images/GAMES ICON/FREEFIRE_iconapp.png',
    bg: '/images/GAMES BG/FREEFIRE_bg.png',
    promoBg: '/images/BG_UID/FF.png',
    promoAspect: '33 / 14',
    promoFade: true,
    howtoImage: '/images/HOW%20TO/ff.png',
    category: 'เกม Battle Royale',
    currency: 'เพชร',
    tag: 'ขายดี',
    showOnHome: true,
    tags: ['โปรโมชั่น', 'ขายดี'],
    packages: [
      { id: 1,  amount: 33,    price: 10,   bonus: '+3',    img: `${FF_BASE}/diamond1_freefire.png` },
      { id: 2,  amount: 68,    price: 20,   bonus: '+25',   img: `${FF_BASE}/diamond1_freefire.png` },
      { id: 3,  amount: 0,     price: 32,   bonus: null,    label: 'สมาชิกเพชร รายสัปดาห์มินิ',  detail: 'รับ 200 เพชร', img: `${FF_BASE}/weekly_pass_lite_freefire.png` },
      { id: 4,  amount: 136,   price: 40,   bonus: '+50',   img: `${FF_BASE}/diamond1_freefire.png` },
      { id: 5,  amount: 172,   price: 49,   bonus: '+35',   img: `${FF_BASE}/diamond2_freefire.png` },
      { id: 6,  amount: 204,   price: 59,   bonus: '+75',   img: `${FF_BASE}/diamond2_freefire.png` },
      { id: 7,  amount: 0,     price: 65,   bonus: null,    label: 'สมาชิกเพชร รายสัปดาห์',       detail: 'รับ 450 เพชร', img: `${FF_BASE}/weekly_pass_freefire.png` },
      { id: 8,  amount: 0,     price: 88,   bonus: null,    label: 'บูย่าห์พาส',                   img: `${FF_BASE}/booyah_pass_freefire.png` },
      { id: 9,  amount: 310,   price: 89,   bonus: '+79',   img: `${FF_BASE}/diamond2_freefire.png` },
      { id: 10, amount: 344,   price: 98,   bonus: '+70',   img: `${FF_BASE}/diamond3_freefire.png` },
      { id: 11, amount: 517,   price: 145,  bonus: '+47',   img: `${FF_BASE}/diamond3_freefire.png` },
      { id: 12, amount: 690,   price: 200,  bonus: '+63',   img: `${FF_BASE}/diamond3_freefire.png` },
      { id: 13, amount: 860,   price: 245,  bonus: '+175',  img: `${FF_BASE}/diamond4_freefire.png` },
      { id: 14, amount: 930,   price: 264,  bonus: '+237',  img: `${FF_BASE}/diamond4_freefire.png` },
      { id: 15, amount: 0,     price: 288,  bonus: null,    label: 'สมาชิกเพชร รายเดือน',         detail: 'รับ 2600 เพชร', img: `${FF_BASE}/monthly_pass_freefire.png` },
      { id: 16, amount: 1052,  price: 288,  bonus: '+96',   img: `${FF_BASE}/diamond4_freefire.png` },
      { id: 17, amount: 1240,  price: 347,  bonus: '+316',  img: `${FF_BASE}/diamond4_freefire.png` },
      { id: 18, amount: 1380,  price: 400,  bonus: '+126',  img: `${FF_BASE}/diamond5_freefire.png` },
      { id: 19, amount: 1551,  price: 430,  bonus: '+141',  img: `${FF_BASE}/diamond5_freefire.png` },
      { id: 20, amount: 1801,  price: 480,  bonus: '+164',  img: `${FF_BASE}/diamond5_freefire.png` },
      { id: 21, amount: 2104,  price: 580,  bonus: '+192',  img: `${FF_BASE}/diamond5_freefire.png` },
      { id: 22, amount: 3156,  price: 860,  bonus: '+288',  img: `${FF_BASE}/diamond5_freefire.png` },
      { id: 23, amount: 3698,  price: 950,  bonus: '+337',  img: `${FF_BASE}/diamond5_freefire.png` },
      { id: 24, amount: 4208,  price: 1145, bonus: '+384',  img: `${FF_BASE}/diamond6_freefire.png` },
      { id: 25, amount: 5403,  price: 1425, bonus: '+492',  img: `${FF_BASE}/diamond6_freefire.png` },
      { id: 26, amount: 7204,  price: 1890, bonus: '+656',  img: `${FF_BASE}/diamond6_freefire.png` },
      { id: 27, amount: 7396,  price: 1900, bonus: '+674',  img: `${FF_BASE}/diamond6_freefire.png` },
      { id: 28, amount: 11094, price: 2850, bonus: '+1011', img: `${FF_BASE}/diamond6_freefire.png` },
      { id: 29, amount: 14792, price: 3800, bonus: '+1348', img: `${FF_BASE}/diamond6_freefire.png` },
      { id: 30, amount: 18490, price: 4750, bonus: '+1685', img: `${FF_BASE}/diamond6_freefire.png` },
      { id: 31, amount: 22188, price: 5700, bonus: '+2022', img: `${FF_BASE}/diamond6_freefire.png` },
      { id: 32, amount: 25886, price: 6650, bonus: '+2359', img: `${FF_BASE}/diamond6_freefire.png` },
      { id: 33, amount: 29584, price: 7600, bonus: '+2696', img: `${FF_BASE}/diamond6_freefire.png` },
      { id: 34, amount: 33282, price: 8550, bonus: '+3033', img: `${FF_BASE}/diamond6_freefire.png` },
      { id: 35, amount: 36980, price: 9500, bonus: '+3370', img: `${FF_BASE}/diamond6_freefire.png` },
    ],
  },

  'PUBG Mobile': {
    id: 'PUBG Mobile',
    name: 'PUBG Mobile',
    subtitle: 'PUBG Mobile — เติม UC',
    icon: '/images/GAMES ICON/PUBGMOBILE_iconapp.png',
    bg: '/images/GAMES BG/PUBGMOBILE_bg.png',
    category: 'เกม Battle Royale',
    currency: 'UC',
    tag: null,
    showOnHome: true,
    tags: ['โปรโมชั่น', 'ขายดี'],
    packages: [
      { id: 1, amount: 60,   price: 35,   bonus: null,    img: `${PUBGM_BASE}/uc_pubgmobile.png` },
      { id: 2, amount: 325,  price: 169,  bonus: '+25',   img: `${PUBGM_BASE}/uc_pubgmobile.png` },
      { id: 3, amount: 660,  price: 329,  bonus: '+60',   img: `${PUBGM_BASE}/uc_pubgmobile.png` },
      { id: 4, amount: 1800, price: 899,  bonus: '+180',  img: `${PUBGM_BASE}/uc_pubgmobile.png` },
      { id: 5, amount: 3850, price: 1899, bonus: '+385',  img: `${PUBGM_BASE}/uc_pubgmobile.png` },
      { id: 6, amount: 8100, price: 3799, bonus: '+810',  img: `${PUBGM_BASE}/uc_pubgmobile.png` },
    ],
  },

  // ══════════════════════════════════════════
  //  เกมยิง FPS
  // ══════════════════════════════════════════

  'Call of Duty': {
    id: 'Call of Duty',
    name: 'Call of Duty',
    subtitle: 'Call of Duty Mobile — เติม CP',
    icon: '/images/GAMES ICON/CALLOFDUTY_iconapp.png',
    bg: '/images/GAMES BG/CALLOFDUTY_bg.png',
    category: 'เกมยิง FPS',
    currency: 'CP',
    tag: null,
    showOnHome: true,
    tags: ['โปรโมชั่น', 'ขายดี'],
    packages: [
      { id: 'cod-48',   amount: 44,   bonus: '+4',   price: 30,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/callofduty_cp.png' },
      { id: 'cod-126',  amount: 108,  bonus: '+18',  price: 49,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/callofduty_cp.png' },
      { id: 'cod-227',  amount: 194,  bonus: '+33',  price: 89,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/callofduty_cp.png' },
      { id: 'cod-252',  amount: 237,  bonus: '+15',  price: 99,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/callofduty_cp.png' },
      { id: 'cod-378',  amount: 324,  bonus: '+54',  price: 145, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/callofduty_cp.png' },
      { id: 'cod-792',  amount: 648,  bonus: '+144', price: 288, badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/callofduty_cp.png' },
      { id: 'cod-1440', amount: 1080, bonus: '+360', price: 480, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/callofduty_cp.png' },
      { id: 'cod-3000', amount: 2160, bonus: '+840', price: 950, badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/callofduty_cp.png' },
    ],
  },

  'Delta Force': {
    id: 'Delta Force',
    name: 'Delta Force',
    subtitle: 'Delta Force: Hawk Ops — เติม DF Points',
    icon: '/images/GAMES ICON/DELTAFORCE_iconapp.png',
    bg: '/images/GAMES BG/DELTAFORCE_bg.png',
    category: 'เกมยิง FPS',
    currency: 'DF Points',
    tag: 'ใหม่',
    showOnHome: true,
    packages: [
      { id: 'df-18',       amount: 18,                                   price: 12,    img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'df-30',       amount: 30,                                   price: 19,    img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'df-60',       amount: 60,                                   price: 34,    img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'df-300',      amount: 0, label: '300 + 20 Delta Coin',      price: 139,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'df-420',      amount: 0, label: '420 + 40 Delta Coin',      price: 199,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'df-680',      amount: 0, label: '680 + 70 Delta Coin',      price: 269,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'df-1280',     amount: 0, label: '1,280 + 200 Delta Coin',   price: 519,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'df-1680',     amount: 0, label: '1,680 + 300 Delta Coin',   price: 649,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'df-3280',     amount: 0, label: '3,280 + 670 Delta Coin',   price: 1279,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'df-6480',     amount: 0, label: '6,480 + 1,620 Delta Coin', price: 2499,  badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
    ],
  },

  'Delta Force Steam': {
    id: 'Delta Force Steam',
    name: 'Delta Force Steam',
    subtitle: 'Delta Force (Steam) — เติม Delta Coin',
    icon: '/images/GAMES ICON/DELTAFORCE_iconapp.png',
    bg: '/images/GAMES BG/DELTAFORCE_bg.png',
    category: 'เกมยิง FPS',
    currency: 'Delta Coin',
    tag: 'ใหม่',
    showOnHome: true,
    packages: [
      { id: 'dfs-18',      amount: 18,    price: 12,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'dfs-31',      amount: 30,    bonus: '+1',    price: 15,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'dfs-blaze',   amount: 0,     label: 'Blaze Supplies',          price: 19,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'dfs-genesis', amount: 0,     label: 'Genesis Supplies',        price: 20,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'dfs-60',      amount: 60,    price: 27,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'dfs-blazeadv',amount: 0,     label: 'Blaze Supplies Advanced', price: 48,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'dfs-320',     amount: 300,   bonus: '+20',   price: 131,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'dfs-460',     amount: 420,   bonus: '+40',   price: 180,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'dfs-op',      amount: 0,     label: 'Operation Special',       price: 210,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'dfs-war',     amount: 0,     label: 'Warfare Special',         price: 215,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'dfs-750',     amount: 680,   bonus: '+70',   price: 260,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'dfs-1480',    amount: 1280,  bonus: '+200',  price: 519,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'dfs-1980',    amount: 1680,  bonus: '+300',  price: 649,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'dfs-3950',    amount: 3280,  bonus: '+670',  price: 1299, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'dfs-8100',    amount: 6480,  bonus: '+1620', price: 2590, badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'dfs-16848',   amount: 12960, bonus: '+3888', price: 5275, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
      { id: 'dfs-25272',   amount: 19440, bonus: '+5832', price: 7900, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Deltaforce_coin.png' },
    ],
  },

  'Blood Strike': {
    id: 'Blood Strike',
    name: 'Blood Strike',
    subtitle: 'Blood Strike — เติม Gold',
    icon: '/images/GAMES ICON/BLOODSTRIKE_iconapp.png',
    bg: '/images/GAMES BG/BLOODSTRIKE_bg.png',
    category: 'เกมยิง FPS',
    currency: 'Gold',
    tag: 'ใหม่',
    showOnHome: true,
    packages: [
      { id: 'bs-lucky-skin', amount: 0, label: 'Ultra Skin Lucky Chest',          price: 15,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE ICON/BLOOD STRIKE/bloodstrike_UltraSkinLuckyChest.png' },
      { id: 'bs-105',        amount: 100, bonus: '+5',                             price: 25,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE ICON/BLOOD STRIKE/Bloodstrike_gold.png' },
      { id: 'bs-lucky-bag',  amount: 0, label: 'Lucky Bag Week',                  price: 29,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE ICON/BLOOD STRIKE/bloodstrike__Lucky Bag Week.png' },
      { id: 'bs-season',     amount: 0, label: 'Season Pass',                     price: 36,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE ICON/BLOOD STRIKE/bloodstrike_SeasonPass.png' },
      { id: 'bs-levelup',    amount: 0, label: 'Level Up Pass',                   price: 52,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE ICON/BLOOD STRIKE/bloodstrike_LevelUpPass.png' },
      { id: 'bs-bleach',     amount: 0, label: 'BLEACH Upgrade Point Chest',      price: 59,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE ICON/BLOOD STRIKE/bloodstrike_BLEACHUpgradePointChest.png' },
      { id: 'bs-7ds',        amount: 0, label: 'Seven Deadly Sins Chest x10',     price: 69,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE ICON/BLOOD STRIKE/bloodstrike_ChestUpgradePointSevenDeadlySins.png' },
      { id: 'bs-320',        amount: 300, bonus: '+20',                            price: 70,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE ICON/BLOOD STRIKE/Bloodstrike_gold.png' },
      { id: 'bs-elite',      amount: 0, label: 'Strike Pass Elite',               price: 102,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE ICON/BLOOD STRIKE/bloodstrike_StrikePassElite.png' },
      { id: 'bs-540',        amount: 500, bonus: '+40',                            price: 115,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE ICON/BLOOD STRIKE/Bloodstrike_gold.png' },
      { id: 'bs-premium',    amount: 0, label: 'Strike Pass Premium',             price: 230,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE ICON/BLOOD STRIKE/bloodstrike_StrikePassPremium.png' },
      { id: 'bs-1100',       amount: 1000, bonus: '+100',                          price: 230,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE ICON/BLOOD STRIKE/Bloodstrike_gold.png' },
      { id: 'bs-2260',       amount: 2000, bonus: '+260',                          price: 456,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE ICON/BLOOD STRIKE/Bloodstrike_gold.png' },
      { id: 'bs-5800',       amount: 5000, bonus: '+800',                          price: 1140, badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE ICON/BLOOD STRIKE/Bloodstrike_gold.png' },
    ],
  },

  'Ballistic Hero': {
    id: 'Ballistic Hero',
    name: 'Ballistic Hero',
    subtitle: 'Ballistic Hero — เติม Diamond',
    icon: '/images/GAMES ICON/BALLISTICHERO_iconapp.png',
    bg: '/images/GAMES BG/BALLISTICHERO_bg.png',
    category: 'เกมยิง FPS',
    currency: 'Diamond',
    tag: 'ใหม่',
    showOnHome: true,
    packages: [
      { id: 'bh-60',    amount: 60,    price: 32,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/BallisticHero_voucher.png' },
      { id: 'bh-300',   amount: 300,   price: 159,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/BallisticHero_voucher.png' },
      { id: 'bh-600',   amount: 600,   price: 299,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/BallisticHero_voucher.png' },
      { id: 'bh-1200',  amount: 1200,  price: 630,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/BallisticHero_voucher.png' },
      { id: 'bh-3000',  amount: 3000,  price: 1550, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/BallisticHero_voucher.png' },
      { id: 'bh-6000',  amount: 6000,  price: 3120, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/BallisticHero_voucher.png' },
      { id: 'bh-12000', amount: 12000, price: 5899, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/BallisticHero_voucher.png' },
      { id: 'bh-18000', amount: 18000, price: 8900, badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/BallisticHero_voucher.png' },
    ],
  },

  // ══════════════════════════════════════════
  //  เกมยิงกลยุทธ์
  // ══════════════════════════════════════════

  'Valorant': {
    id: 'Valorant',
    name: 'Valorant',
    subtitle: 'Valorant — เติม Valorant Point',
    icon: '/images/GAMES ICON/VALORANT_iconapp.png',
    bg: '/images/GAMES BG/VALORANT_bg.png',
    category: 'เกมยิงกลยุทธ์',
    currency: 'VP',
    tag: 'ขายดี',  // แก้แท็กเกมในหน้า UID TOP Up เช่น ขายดี , ใหม่ 
    showOnHome: true,
    packages: [
      // ── Rogue Collection Bundles ──────────────────────────────
      { id: 'vp-rogue-gun',    amount: 0, label: '2,525 VP (Rogue Collection ปืนแยกชิ้น)', price: 628,   originalPrice: 650,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Valorant_points.png' },
      { id: 'vp-rogue-melee',  amount: 0, label: '4,650 VP (Rogue Collection Melee)',       price: 1133,  originalPrice: 1180,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Valorant_points.png' },
      { id: 'vp-rogue-bundle', amount: 0, label: '9,000 VP (Rogue Collection Bundle)',      price: 2153,  originalPrice: 2240,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Valorant_points.png' },
      // ── Valorant Points ──────────────────────────────────────
      { id: 'vp-475',    amount: 475,    price: 129,   originalPrice: 130,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Valorant_points.png' },
      { id: 'vp-1000',   amount: 1000,   price: 249,   originalPrice: 279,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Valorant_points.png' },
      { id: 'vp-1475',   amount: 1475,   price: 378,   originalPrice: 390,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Valorant_points.png' },
      { id: 'vp-2050',   amount: 2050,   price: 499,   originalPrice: 559,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Valorant_points.png' },
      { id: 'vp-3050',   amount: 3050,   price: 748,   originalPrice: 830,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Valorant_points.png' },
      { id: 'vp-3650',   amount: 3650,   price: 884,   originalPrice: 920,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Valorant_points.png' },
      { id: 'vp-5350',   amount: 5350,   price: 1269,  originalPrice: 1400,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Valorant_points.png' },
      { id: 'vp-7400',   amount: 7400,   price: 1768,  originalPrice: 1959,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Valorant_points.png' },
      { id: 'vp-10000',  amount: 10000,  price: 2402,  originalPrice: 2650,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Valorant_points.png' },
      { id: 'vp-11000',  amount: 11000,  price: 2534,  originalPrice: 2640,  badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Valorant_points.png' },
    ],
  },

  'Arena Breakout': {
    id: 'Arena Breakout',
    name: 'Arena Breakout',
    subtitle: 'Arena Breakout — เติม Bonds',
    icon: '/images/GAMES ICON/ARENABREAKOUT_iconapp.png',
    bg: '/images/GAMES BG/ARENABREAKOUT_bg.png',
    category: 'เกมยิงกลยุทธ์',
    currency: 'Bonds',
    tag: null,
    showOnHome: true,
    packages: [
      // ── Passes & Privileges ──────────────────────────────────
      { id: 'ab-pass-beginner',    amount: 0, label: 'Beginner Select',                          price: 25,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/ARENA%20BREAKOUT/Arena%20Breakout_BeginnerSelect.png' },
      { id: 'ab-pass-monthly-adv', amount: 0, label: 'Monthly Advanced Battle Pass',             price: 32,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/ARENA%20BREAKOUT/Arena%20Breakout_AdvancedBattlePass.png' },
      { id: 'ab-case-bullet',      amount: 0, label: 'Bulletproof Case Privileges (30 วัน)',     price: 75,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/ARENA%20BREAKOUT/Arena%20Breakout_BulletproofCase.png' },
      { id: 'ab-pass-monthly-pre', amount: 0, label: 'Monthly Premium Battle Pass',              price: 125,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/ARENA%20BREAKOUT/Arena%20Breakout_PremiumBattlePass.png' },
      { id: 'ab-case-composite',   amount: 0, label: 'Composite Case Privileges (30 วัน)',       price: 235,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/ARENA%20BREAKOUT/Arena%20Breakout_CompositeCase.png' },
      { id: 'ab-pass-quarterly',   amount: 0, label: 'Quarterly Premium Battle Pass',            price: 369,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/ARENA%20BREAKOUT/Arena%20Breakout_QuarterlyPremiumBattlePass.png' },
      // ── Bonds ────────────────────────────────────────────────
      { id: 'ab-66',   amount: 60,   bonus: '+6',   price: 29,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/ARENA%20BREAKOUT/Arena%20Breakout_bonds.png' },
      { id: 'ab-335',  amount: 310,  bonus: '+25',  price: 131,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/ARENA%20BREAKOUT/Arena%20Breakout_bonds.png' },
      { id: 'ab-675',  amount: 630,  bonus: '+45',  price: 269,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/ARENA%20BREAKOUT/Arena%20Breakout_bonds.png' },
      { id: 'ab-1690', amount: 1580, bonus: '+110', price: 660,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/ARENA%20BREAKOUT/Arena%20Breakout_bonds.png' },
      { id: 'ab-3400', amount: 3200, bonus: '+200', price: 1310, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/ARENA%20BREAKOUT/Arena%20Breakout_bonds.png' },
      { id: 'ab-6820', amount: 6500, bonus: '+320', price: 2570, badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/ARENA%20BREAKOUT/Arena%20Breakout_bonds.png' },
    ],
  },

  // ══════════════════════════════════════════
  //  เกม RPG
  // ══════════════════════════════════════════

  'Honkai: Star Rail': {
    id: 'Honkai: Star Rail',
    name: 'Honkai: Star Rail',
    subtitle: 'Honkai: Star Rail — เติม Oneiric Shard',
    icon: '/images/GAMES ICON/STARRAIL_iconapp.png',
    bg: '/images/GAMES BG/STARRAIL_bg.png',
    category: 'เกม RPG',
    currency: 'Oneiric Shard',
    tag: null,
    showOnHome: true,
    packages: [
      { id: 'hsr-60',   amount: 60,   price: 30,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/STARRAIL/starrail_shard.png' },
      { id: 'hsr-330',  amount: 300,  bonus: '+30',   price: 135,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/STARRAIL/starrail_shard.png' },
      { id: 'hsr-pass', amount: 0,    label: 'Express Supply Pass', price: 145,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/STARRAIL/starrail_ExpressSupplyPass.png' },
      { id: 'hsr-1090', amount: 980,  bonus: '+110',  price: 369,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/STARRAIL/starrail_shard.png' },
      { id: 'hsr-1420', amount: 1280, bonus: '+140',  price: 465,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/STARRAIL/starrail_shard.png' },
      { id: 'hsr-2240', amount: 1980, bonus: '+260',  price: 890,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/STARRAIL/starrail_shard.png' },
      { id: 'hsr-3880', amount: 3280, bonus: '+600',  price: 1180, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/STARRAIL/starrail_shard.png' },
      { id: 'hsr-8080', amount: 6480, bonus: '+1600', price: 2550, badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/STARRAIL/starrail_shard.png' },
    ],
  },

  'Aether Gazer': {
    id: 'Aether Gazer',
    name: 'Aether Gazer',
    subtitle: 'Aether Gazer — เติม Shifting Flowers',
    icon: '/images/GAMES ICON/AETHERGAZER_iconapp.png',
    bg: '/images/GAMES BG/AETHERGAZER_bg.png',
    category: 'เกม RPG',
    currency: 'Shifting Flowers',
    tag: null,
    showOnHome: true,
    packages: [
      { id: 'ag-60',   amount: 60,   price: 30,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Aethergazer_flowers.png' },
      { id: 'ag-490',  amount: 490,  price: 255,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Aethergazer_flowers.png' },
      { id: 'ag-990',  amount: 990,  price: 470,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Aethergazer_flowers.png' },
      { id: 'ag-1990', amount: 1990, price: 930,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Aethergazer_flowers.png' },
      { id: 'ag-2990', amount: 2990, price: 1450, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Aethergazer_flowers.png' },
      { id: 'ag-6000', amount: 6000, price: 2790, badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Aethergazer_flowers.png' },
    ],
  },

  'AFK Journey': {
    id: 'AFK Journey',
    name: 'AFK Journey',
    subtitle: 'AFK Journey — เติม Dragon Crystal',
    icon: '/images/GAMES ICON/AFKJOURNEY_iconapp.png',
    bg: '/images/GAMES BG/AFKJOURNEY_bg.png',
    category: 'เกม RPG',
    currency: 'Dragon Crystal',
    tag: null,
    showOnHome: true,
    packages: [
      { id: 'afk-21',      amount: 20,   bonus: '+1',   price: 33,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/AFK%20JOURNEY/afkjourney_dragoncrytals.png' },
      { id: 'afk-classic', amount: 0,    label: 'Esperia Monthly — Classic Gazette',  price: 155,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/AFK%20JOURNEY/afkjourney_ClassicGazette.png' },
      { id: 'afk-126',     amount: 120,  bonus: '+6',   price: 155,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/AFK%20JOURNEY/afkjourney_dragoncrytals.png' },
      { id: 'afk-294',     amount: 280,  bonus: '+14',  price: 305,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/AFK%20JOURNEY/afkjourney_dragoncrytals.png' },
      { id: 'afk-premium', amount: 0,    label: 'Esperia Monthly — Premium Gazette',  price: 475,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/AFK%20JOURNEY/afkjourney_PremiumGazette.png' },
      { id: 'afk-588',     amount: 560,  bonus: '+28',  price: 630,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/AFK%20JOURNEY/afkjourney_dragoncrytals.png' },
      { id: 'afk-growth',  amount: 0,    label: 'Growth Bundle',                      price: 950,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/AFK%20JOURNEY/afkjourney_GrowthBundle.png' },
      { id: 'afk-1554',    amount: 1480, bonus: '+74',  price: 1500, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/AFK%20JOURNEY/afkjourney_dragoncrytals.png' },
      { id: 'afk-3150',    amount: 3000, bonus: '+150', price: 2950, badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/AFK%20JOURNEY/afkjourney_dragoncrytals.png' },
    ],
  },

  'Bleach': {
    id: 'Bleach',
    name: 'Bleach',
    subtitle: 'Bleach: Soul Resonance — เติม Spiritual Jade',
    icon: '/images/GAMES ICON/BLEACH_iconapp.png',
    bg: '/images/GAMES BG/BLEACH_bg.png',
    category: 'เกม RPG',
    currency: 'Spiritual Jade',
    tag: null,
    showOnHome: true,
    packages: [
      { id: 'bl-60',    amount: 60,    price: 29,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/BLEACH/bleach_PremiumSpiritualJade.png' },
      { id: 'bl-card',  amount: 0,    label: 'Monthly Card Membership',  price: 142,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/BLEACH/bleach_MonthlyCardMembership.png' },
      { id: 'bl-300',   amount: 300,   price: 143,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/BLEACH/bleach_PremiumSpiritualJade.png' },
      { id: 'bl-980',   amount: 980,   price: 437,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/BLEACH/bleach_PremiumSpiritualJade.png' },
      { id: 'bl-1980',  amount: 1980,  price: 799,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/BLEACH/bleach_PremiumSpiritualJade.png' },
      { id: 'bl-3280',  amount: 3280,  price: 1340, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/BLEACH/bleach_PremiumSpiritualJade.png' },
      { id: 'bl-6480',  amount: 6480,  price: 2640, badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/BLEACH/bleach_PremiumSpiritualJade.png' },
      { id: 'bl-12800', amount: 12800, price: 5230, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/BLEACH/bleach_PremiumSpiritualJade.png' },
    ],
  },

  'Where Winds Meet': {
    id: 'Where Winds Meet',
    name: 'Where Winds Meet',
    subtitle: 'Where Winds Meet — เติม Echo Beads',
    icon: '/images/GAMES ICON/WHEREWINDMEET_iconapp.png',
    bg: '/images/GAMES BG/WHEREWINDMEET_bg.png',
    category: 'เกม RPG',
    currency: 'Echo Beads',
    tag: 'มาแรง',
    showOnHome: true,
    tags: ['ขายดี'],
    packages: [
      { id: 'wwm-60',    amount: 60,    price: 29,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Wherewindmeet_echo.png' },
      { id: 'wwm-180',   amount: 180,   price: 90,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Wherewindmeet_echo.png' },
      { id: 'wwm-300',   amount: 300,   price: 149,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Wherewindmeet_echo.png' },
      { id: 'wwm-600',   amount: 600,   price: 298,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Wherewindmeet_echo.png' },
      { id: 'wwm-900',   amount: 900,   price: 452,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Wherewindmeet_echo.png' },
      { id: 'wwm-1800',  amount: 1800,  price: 901,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Wherewindmeet_echo.png' },
      { id: 'wwm-3000',  amount: 3000,  price: 1492, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Wherewindmeet_echo.png' },
      { id: 'wwm-6000',  amount: 6000,  price: 2975, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Wherewindmeet_echo.png' },
      { id: 'wwm-12000', amount: 12000, price: 5920, badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Wherewindmeet_echo.png' },
    ],
  },

  // ══════════════════════════════════════════
  //  เกมแข่งรถ
  // ══════════════════════════════════════════

  'ACE RACER': {
    id: 'ACE RACER',
    name: 'ACE RACER',
    subtitle: 'ACE RACER — เติม Token',
    icon: '/images/GAMES ICON/ACERACER_iconapp.png',
    bg: '/images/GAMES BG/ACERACER_bg.png',
    category: 'เกมแข่งรถ',
    currency: 'Token',
    tag: null,
    showOnHome: true,
    packages: [
      { id: 'ar-65',   amount: 60,   bonus: '+5',   price: 30,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Aceracer_tokens.png' },
      { id: 'ar-270',  amount: 250,  bonus: '+20',  price: 122,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Aceracer_tokens.png' },
      { id: 'ar-740',  amount: 680,  bonus: '+60',  price: 297,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Aceracer_tokens.png' },
      { id: 'ar-1300', amount: 1180, bonus: '+120', price: 558,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Aceracer_tokens.png' },
      { id: 'ar-3180', amount: 2880, bonus: '+300', price: 1396, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Aceracer_tokens.png' },
      { id: 'ar-6530', amount: 5880, bonus: '+650', price: 2570, badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Aceracer_tokens.png' },
    ],
  },

  // ══════════════════════════════════════════
  //  สตรีมมิ่ง
  // ══════════════════════════════════════════

  'BIGO LIVE': {
    id: 'BIGO LIVE',
    name: 'BIGO LIVE',
    subtitle: 'BIGO LIVE — เติม Diamond',
    icon: '/images/GAMES ICON/BIGOLIVE_iconapp.png',
    bg: '/images/GAMES BG/BIGOLIVE_bg.png',
    category: 'สตรีมมิ่ง',
    currency: 'Diamond',
    tag: null,
    showOnHome: true,
    packages: [
      { id: 'bigo-10',    amount: 10,    price: 10,    img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Bigo_diamonds.png' },
      { id: 'bigo-20',    amount: 20,    price: 17,    img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Bigo_diamonds.png' },
      { id: 'bigo-40',    amount: 40,    price: 30,    img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Bigo_diamonds.png' },
      { id: 'bigo-50',    amount: 50,    price: 39,    img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Bigo_diamonds.png' },
      { id: 'bigo-80',    amount: 80,    price: 57,    img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Bigo_diamonds.png' },
      { id: 'bigo-100',   amount: 100,   price: 79,    img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Bigo_diamonds.png' },
      { id: 'bigo-200',   amount: 200,   price: 160,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Bigo_diamonds.png' },
      { id: 'bigo-500',   amount: 500,   price: 349,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Bigo_diamonds.png' },
      { id: 'bigo-1000',  amount: 1000,  price: 710,   badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Bigo_diamonds.png' },
      { id: 'bigo-2000',  amount: 2000,  price: 1300,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Bigo_diamonds.png' },
      { id: 'bigo-4000',  amount: 4000,  price: 2650,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Bigo_diamonds.png' },
      { id: 'bigo-5000',  amount: 5000,  price: 3250,  badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Bigo_diamonds.png' },
      { id: 'bigo-8000',  amount: 8000,  price: 5150,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Bigo_diamonds.png' },
      { id: 'bigo-10000', amount: 10000, price: 7000,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Bigo_diamonds.png' },
      { id: 'bigo-16000', amount: 16000, price: 10000, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Bigo_diamonds.png' },
      { id: 'bigo-20000', amount: 20000, price: 13000, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Bigo_diamonds.png' },
      { id: 'bigo-24000', amount: 24000, price: 15200, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Bigo_diamonds.png' },
      { id: 'bigo-40000', amount: 40000, price: 25500, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/Bigo_diamonds.png' },
    ],
  },

  // ══════════════════════════════════════════
  //  เกมกีฬา
  // ══════════════════════════════════════════

  'Dunk City Dynasty': {
    id: 'Dunk City Dynasty',
    name: 'Dunk City Dynasty',
    subtitle: 'Dunk City Dynasty — เติม Token',
    icon: '/images/GAMES ICON/DUNKCITY_iconapp.png',
    bg: '/images/GAMES BG/DUNKCITY_bg.png',
    category: 'เกมกีฬา',
    currency: 'Token',
    tag: null,
    showOnHome: true,
    packages: [
      { id: 'dc-60',     amount: 60,   price: 27,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/DUNK%20CITY/dunkcity_tokens.png' },
      { id: 'dc-rookie', amount: 0,    label: 'Rookie Gift Pack',    price: 90,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/DUNK%20CITY/dunkcity_RookieGiftPack.png' },
      { id: 'dc-330',    amount: 300,  bonus: '+30',  price: 149,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/DUNK%20CITY/dunkcity_tokens.png' },
      { id: 'dc-party',  amount: 0,    label: 'Party Membership',    price: 168,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/DUNK%20CITY/dunkcity_PartyMembership.png' },
      { id: 'dc-prem',   amount: 0,    label: 'Premium Pass',        price: 169,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/DUNK%20CITY/dunkcity_PremiumPass.png' },
      { id: 'dc-extprem',amount: 0,    label: 'Extra Premium Pass',  price: 248,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/DUNK%20CITY/dunkcity_ExtraPremiumPass.png' },
      { id: 'dc-1110',   amount: 980,  bonus: '+130', price: 436,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/DUNK%20CITY/dunkcity_tokens.png' },
      { id: 'dc-vip',    amount: 0,    label: 'Party Permanent VIP', price: 444,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/DUNK%20CITY/dunkcity_tokens.png' },
      { id: 'dc-2280',   amount: 1980, bonus: '+300', price: 970,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/DUNK%20CITY/dunkcity_tokens.png' },
      { id: 'dc-3880',   amount: 3280, bonus: '+600', price: 1620, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/DUNK%20CITY/dunkcity_tokens.png' },
      { id: 'dc-8110',   amount: 6480, bonus: '+1630',price: 2600, badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/DUNK%20CITY/dunkcity_tokens.png' },
    ],
  },

  'FC Mobile': {
    id: 'FC Mobile',
    name: 'FC Mobile',
    subtitle: 'EA SPORTS FC Mobile — เติม FC Points',
    icon: '/images/GAMES ICON/FCMOBILE_iconapp.png',
    bg: '/images/GAMES BG/FCMOBILE_bg.png',
    category: 'เกมกีฬา',
    currency: 'FC Points',
    tag: 'ขายดี',
    showOnHome: true,
    accountFields: [
      { key: 'uid', label: 'Player ID', placeholder: 'เช่น 123456789', inputMode: 'numeric', required: true },
    ],
    accountHint: 'Player ID ดูได้ที่เมนูโปรไฟล์ในเกม',
    packages: [
      { id: 'fc-100',   amount: 100,   price: 20,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-200',   amount: 200,   price: 39,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-300',   amount: 300,   price: 59,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-500',   amount: 500,   price: 95,   badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-750',   amount: 750,   price: 140,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-1000',  amount: 1000,  price: 185,  badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-1500',  amount: 1500,  price: 279,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-3000',  amount: 3000,  price: 558,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-5000',  amount: 5000,  price: 920,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-7500',  amount: 7500,  price: 1370, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-10000', amount: 10000, price: 1820, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-15000', amount: 15000, price: 2740, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-20000', amount: 20000, price: 3640, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-30000', amount: 30000, price: 5460, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-50000', amount: 50000, price: 9100, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
    ],
  },

  // ══════════════════════════════════════════
  //  เกมจำลอง
  // ══════════════════════════════════════════

  'Heartopia': {
    id: 'Heartopia',
    name: 'Heartopia',
    subtitle: 'Heartopia — เติม เพชรหัวใจ',
    icon: '/images/GAMES ICON/HEARTOPIA_iconapp.png',
    bg: '/images/GAMES BG/HEARTOPIA_bg.png',
    category: 'เกมจำลอง',
    currency: 'เพชรหัวใจ',
    tag: null,
    showOnHome: true,
    accountFields: [
      { key: 'uid', label: 'Player ID', placeholder: 'เช่น 123456789', inputMode: 'numeric', required: true },
    ],
    accountHint: 'Player ID ดูได้ที่เมนูโปรไฟล์ในเกม',
    packages: [
      { id: 'ht-20',       amount: 20,   price: 20,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/Heartopia_candy.png' },
      { id: 'ht-pass7',    amount: 0,    label: 'สมาชิกสมาคมลูกโอ๊กระดับต้น',  price: 25,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/heartopia_pass7.png' },
      { id: 'ht-60',       amount: 60,   price: 39,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/Heartopia_candy.png' },
      { id: 'ht-pass30',   amount: 0,    label: 'สมาชิกทางการลูกโอ๊กทองคำ',    price: 101,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/heartopia_pass30.png' },
      { id: 'ht-festival', amount: 0,    label: 'Festival Pack',                 price: 171,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/heartopia_FestivalPack.png' },
      { id: 'ht-320',      amount: 300,  bonus: '+20',  price: 172,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/heartopia_FestivalPack.png' },
      { id: 'ht-festup',   amount: 0,    label: 'Festival Pack Upgrade',         price: 199,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/heartopia_FestivalPackUP.png' },
      { id: 'ht-730',      amount: 680,  bonus: '+50',  price: 335,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/heartopia_FestivalPack.png' },
      { id: 'ht-supreme',  amount: 0,    label: 'Supreme Festival Pack',         price: 341,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/heartopia_SupremeFestivalPack.png' },
      { id: 'ht-1370',     amount: 1280, bonus: '+90',  price: 625,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/heartopia_FestivalPackUP.png' },
      { id: 'ht-2130',     amount: 1980, bonus: '+150', price: 969,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/heartopia_FestivalPackUP.png' },
      { id: 'ht-3550',     amount: 3280, bonus: '+270', price: 1590, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/heartopia_SupremeFestivalPack.png' },
      { id: 'ht-7050',     amount: 6480, bonus: '+570', price: 3079, badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/heartopia_SupremeFestivalPack.png' },
    ],
  },

  // ══════════════════════════════════════════
  //  เกมเอาชีวิตรอด
  // ══════════════════════════════════════════

  'Identity V': {
    id: 'Identity V',
    name: 'Identity V',
    subtitle: 'Identity V — เติม Extra Echoes',
    icon: '/images/GAMES ICON/IDENTITYV_iconapp.png',
    bg: '/images/GAMES BG/IDENTITYV_bg.png',
    category: 'เกมเอาชีวิตรอด',
    currency: 'Echoes',
    tag: null,
    showOnHome: true,
    packages: [
      { id: 'idv-66',    amount: 60,    bonus: '+6',   price: 28,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/IDENTITY%20V/IdentityV_letter.png' },
      { id: 'idv-inspi', amount: 0,     label: 'Inspirations Package',    price: 33,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/IDENTITY%20V/identityv_InspirationsPackage.png' },
      { id: 'idv-203',   amount: 185,   bonus: '+18',  price: 84,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/IDENTITY%20V/IdentityV_letter.png' },
      { id: 'idv-335',   amount: 305,   bonus: '+30',  price: 140,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/IDENTITY%20V/IdentityV_letter.png' },
      { id: 'idv-clues', amount: 0,     label: 'Clues Package',           price: 166,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/IDENTITY%20V/identityv_CluesPackage.png' },
      { id: 'idv-759',   amount: 690,   bonus: '+69',  price: 285,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/IDENTITY%20V/IdentityV_letter.png' },
      { id: 'idv-memo',  amount: 0,     label: 'Memory Sphere Package',   price: 330,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/IDENTITY%20V/identityv_MemorySpherePackage.png' },
      { id: 'idv-2227',  amount: 2025,  bonus: '+202', price: 856,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/IDENTITY%20V/IdentityV_letter.png' },
      { id: 'idv-3663',  amount: 3330,  bonus: '+333', price: 1426, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/IDENTITY%20V/IdentityV_letter.png' },
      { id: 'idv-7249',  amount: 6590,  bonus: '+659', price: 2850, badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/IDENTITY%20V/IdentityV_letter.png' },
    ],
  },

};
