export const MAILPASS_GAMES = {

  // ══════════════════════════════════════════
  //  เกมฟุตบอล
  // ══════════════════════════════════════════

  'eFootball Android': {
    id: 'eFootball Android',
    name: 'eFootball (Android)',
    subtitle: 'eFootball Android — เติม eFootball Coin',
    icon: '/images/GAMES ICON/EFOOTBALL_iconapp.png',
    bg: '/images/GAMES BG/EFOOTBALL_bg.png',
    promoBg: '/images/MAIL/EFOOBALL.png',
    promoAspect: '21 / 7',
    category: 'เกมฟุตบอล',
    currency: 'eFootball Coin',
    tag: 'ขายดี',
    showOnHome: true,
    tags: [],
    accountFields: [
      { key: 'idLogin',  label: 'ID Login',           placeholder: 'กรุณากรอก ID Login',         hint: 'ไอดีที่ใช้ในการล็อคอิน',        required: true,  type: 'text' },
      { key: 'password', label: 'Password',            placeholder: 'กรุณากรอก Password',          hint: 'พาสเวิร์ดที่ใช้ในการล็อคอิน',   required: true,  type: 'password' },
      { key: 'charName', label: 'ชื่อตัวละคร',        placeholder: 'กรุณากรอกชื่อตัวละครในเกม',  required: true,  type: 'text' },
      { key: 'phone',    label: 'เบอร์โทรติดต่อกลับ', placeholder: 'เบอร์โทร',                    labelHint: 'กรณีลูกค้าต้องการให้โทรแจ้งเมื่อถึงคิว', required: false, type: 'tel' },
    ],
    packages: [
      { id: 'ef-a-550',   amount: 550,   price: 155,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-a-750',   amount: 750,   price: 210,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-a-1040',  amount: 1040,  price: 279,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-a-1590',  amount: 1590,  price: 429,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-a-2130',  amount: 2130,  price: 570,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-a-3250',  amount: 3250,  price: 850,  badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-a-4290',  amount: 4290,  price: 1129, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-a-5700',  amount: 5700,  price: 1450, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-a-6740',  amount: 6740,  price: 1729, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-a-7830',  amount: 7830,  price: 2020, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-a-8950',  amount: 8950,  price: 2300, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-a-12800', amount: 12800, price: 2850, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-a-18500', amount: 18500, price: 4300, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-a-25600', amount: 25600, price: 5700, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
    ],
  },

  'eFootball iOS': {
    id: 'eFootball iOS',
    name: 'eFootball (iOS)',
    subtitle: 'eFootball iOS — เติม eFootball Coin',
    icon: '/images/GAMES ICON/EFOOTBALL_iconapp.png',
    bg: '/images/GAMES BG/EFOOTBALL_bg.png',
    category: 'เกมฟุตบอล',
    currency: 'eFootball Coin',
    tag: null,
    showOnHome: true,
    tags: [],
    accountFields: [
      { key: 'idLogin',  label: 'ID Login',           placeholder: 'กรุณากรอก ID Login',         hint: 'ไอดีที่ใช้ในการล็อคอิน',        required: true,  type: 'text' },
      { key: 'password', label: 'Password',            placeholder: 'กรุณากรอก Password',          hint: 'พาสเวิร์ดที่ใช้ในการล็อคอิน',   required: true,  type: 'password' },
      { key: 'charName', label: 'ชื่อตัวละคร',        placeholder: 'กรุณากรอกชื่อตัวละครในเกม',  required: true,  type: 'text' },
      { key: 'phone',    label: 'เบอร์โทรติดต่อกลับ', placeholder: 'เบอร์โทร',                    labelHint: 'กรณีลูกค้าต้องการให้โทรแจ้งเมื่อถึงคิว', required: false, type: 'tel' },
    ],
    packages: [
      { id: 'ef-i-260',   amount: 260,   price: 35,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-300',   amount: 300,   price: 79,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-550',   amount: 550,   price: 129,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-840',   amount: 840,   price: 135,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-750',   amount: 750,   price: 175,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-1040',  amount: 1040,  price: 235,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-1630',  amount: 1630,  price: 239,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-1100',  amount: 1100,  price: 245,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-1590',  amount: 1590,  price: 350,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-2730',  amount: 2730,  price: 399,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-2130',  amount: 2130,  price: 470,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-2680',  amount: 2680,  price: 580,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-3250',  amount: 3250,  price: 680,  badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-3800',  amount: 3800,  price: 810,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-4290',  amount: 4290,  price: 920,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-5700',  amount: 5700,  price: 1120, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-6740',  amount: 6740,  price: 1360, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-7830',  amount: 7830,  price: 1590, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-8950',  amount: 8950,  price: 1800, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-9990',  amount: 9990,  price: 2030, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-11400', amount: 11400, price: 2250, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-12800', amount: 12800, price: 2330, badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-18500', amount: 18500, price: 3450, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
      { id: 'ef-i-25600', amount: 25600, price: 4650, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/EFOOBALL/ECOIN1.png' },
    ],
  },

  'FC Mobile': {
    id: 'FC Mobile',
    name: 'FC Mobile',
    subtitle: 'EA SPORTS FC Mobile — เติม FC Points',
    icon: '/images/GAMES ICON/FCMOBILE_iconapp.png',
    bg: '/images/GAMES BG/FCMOBILE_bg.png',
    promoBg: '/images/MAIL/FC_FOOBALL3.png',
    promoAspect: '21 / 7',
    category: 'เกมฟุตบอล',
    currency: 'FC Points',
    tag: 'ขายดี',
    showOnHome: true,
    tags: [],
    accountFields: [
      { key: 'idLogin',      label: 'ID Login, facebook หรือ gmail', placeholder: 'กรุณากรอก ID Login, facebook หรือ gmail', hint: 'ไอดีที่ใช้ในการล็อคอิน เช่น Username facebook, gmail เป็นต้น', required: true,  type: 'text' },
      { key: 'password',     label: 'Password',                       placeholder: 'กรุณากรอก Password',                       hint: 'พาสเวิร์ดที่ใช้ในการล็อคอิน',                                   required: true,  type: 'password' },
      { key: 'loginChannel', label: 'ช่องทางการล็อคอินเกม',         placeholder: 'เลือก ช่องทางการล็อคอินเกม',              hint: 'ช่องทางที่ใช้ในการเข้าเกม เช่น ถ้าเข้าเกมด้วยระบบ Facebook จำเป็นต้องใช้รหัสเข้า facebook เพื่อล็อคอิน', required: true,  type: 'select',  options: ['Facebook', 'Google', 'EA Account'] },
      { key: 'charName',     label: 'ชื่อตัวละคร',                  placeholder: 'กรุณากรอกชื่อตัวละครในเกม',                required: true,  type: 'text' },
      { key: 'phone',        label: 'เบอร์โทรติดต่อกลับ',            placeholder: 'เบอร์โทร',                                  labelHint: 'กรณีลูกค้าต้องการให้โทรแจ้งเมื่อถึงคิว', required: false, type: 'tel' },
    ],
    packages: [
      { id: 'fc-40',    amount: 40,    price: 15,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-200',   amount: 200,   price: 33,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-1000',  amount: 1000,  price: 143,  badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-1500',  amount: 1500,  price: 279,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-2000',  amount: 2000,  price: 281,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-4000',  amount: 4000,  price: 554,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-10000', amount: 10000, price: 1360, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-12000', amount: 12000, price: 2720, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
      { id: 'fc-20000', amount: 20000, price: 2730, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FCmobile_coin.png' },
    ],
  },

  // ══════════════════════════════════════════
  //  เกมจำลอง
  // ══════════════════════════════════════════

  'Heartopia': {
    id: 'Heartopia',
    name: 'Heartopia',
    subtitle: 'Heartopia — เติม เพชรหัวใจ',
    icon: '/images/GAMES ICON/HEARTOPIA_iconapp.png',
    bg: '/images/GAMES BG/HEARTOPIA_bg.png',
    category: 'เกมจำลอง',
    currency: 'เพชรหัวใจ',
    tag: null,
    showOnHome: true,
    tags: [],
    accountFields: [
      { key: 'idLogin',      label: 'ID Login, facebook หรือ gmail', placeholder: 'กรุณากรอก ID Login, facebook หรือ gmail', hint: 'ไอดีที่ใช้ในการล็อคอิน เช่น Username facebook, gmail เป็นต้น', required: true,  type: 'text' },
      { key: 'password',     label: 'Password',                       placeholder: 'กรุณากรอก Password',                       hint: 'พาสเวิร์ดที่ใช้ในการล็อคอิน. เช่น รหัสผ่าน facebook หรือ Gmail เป็นต้น', required: true,  type: 'password' },
      { key: 'loginChannel', label: 'ช่องทางการล็อคอินเกม',         placeholder: 'เลือก ช่องทางการล็อคอินเกม',              hint: 'ช่องทางที่ใช้ในการเข้าเกม เช่น ถ้าเข้าเกมด้วยระบบ Facebook จำเป็นต้องใช้รหัสเข้า facebook เพื่อล็อคอิน', required: true,  type: 'select',  options: ['Facebook', 'Email'] /* TODO: เพิ่ม 'Google', 'Apple ID' เมื่อพร้อมรับ */ },
      { key: 'charName',     label: 'ชื่อตัวละคร',                  placeholder: 'กรุณากรอกชื่อตัวละครในเกม',                required: true,  type: 'text' },
      { key: 'phone',        label: 'เบอร์โทรติดต่อกลับ',            placeholder: 'เบอร์โทร',                                  labelHint: 'กรณีลูกค้าต้องการให้โทรแจ้งเมื่อถึงคิว', required: false, type: 'tel' },
    ],
    packages: [
      { id: 'ht-mp-60',    amount: 60,    price: 35,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/Heartopia_candy.png' },
      { id: 'ht-mp-sfp',   amount: 0,     label: 'Supreme Festival Pack',  price: 88,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/heartopia_FestivalPack.png' },
      { id: 'ht-mp-320',   amount: 320,   price: 145,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/Heartopia_candy.png' },
      { id: 'ht-mp-gamg',  amount: 0,     label: 'GAMG Formal Membership', price: 145,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/heartopia_pass30.png' },
      { id: 'ht-mp-730',   amount: 730,   price: 315,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/Heartopia_candy.png' },
      { id: 'ht-mp-fp',    amount: 0,     label: 'Festival Pack',          price: 315,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/heartopia_FestivalPack.png' },
      { id: 'ht-mp-1370',  amount: 1370,  price: 560,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/Heartopia_candy.png' },
      { id: 'ht-mp-2130',  amount: 2130,  price: 860,  badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/Heartopia_candy.png' },
      { id: 'ht-mp-3550',  amount: 3550,  price: 1400, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/Heartopia_candy.png' },
      { id: 'ht-mp-7050',  amount: 7050,  price: 2720, badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/HEATOPIA/Heartopia_candy.png' },
    ],
  },

  // ══════════════════════════════════════════
  //  เกมยิง FPS
  // ══════════════════════════════════════════

  'Call of Duty': {
    id: 'Call of Duty',
    name: 'Call of Duty',
    subtitle: 'Call of Duty Mobile — เติม CP',
    icon: '/images/GAMES ICON/CALLOFDUTY_iconapp.png',
    bg: '/images/GAMES BG/CALLOFDUTY_bg.png',
    category: 'เกมยิง FPS',
    currency: 'CP',
    tag: null,
    showOnHome: true,
    tags: [],
    accountFields: [
      { key: 'idLogin',      label: 'ID Login, facebook หรือ gmail', placeholder: 'กรุณากรอก ID Login, facebook หรือ gmail', hint: 'ไอดีที่ใช้ในการล็อคอิน เช่น Username facebook, gmail เป็นต้น', required: true,  type: 'text' },
      { key: 'password',     label: 'Password',                       placeholder: 'กรุณากรอก Password',                       hint: 'พาสเวิร์ดที่ใช้ในการล็อคอิน. เช่น รหัสผ่าน facebook หรือ Gmail เป็นต้น', required: true,  type: 'password' },
      { key: 'loginChannel', label: 'ช่องทางการล็อคอินเกม',         placeholder: 'เลือก ช่องทางการล็อคอินเกม',              hint: 'ช่องทางที่ใช้ในการเข้าเกม เช่น ถ้าเข้าเกมด้วยระบบ Facebook จำเป็นต้องใช้รหัสเข้า facebook เพื่อล็อคอิน', required: true,  type: 'select',  options: ['Facebook'] /* TODO: เพิ่ม 'Google', 'Activision', 'Apple ID' เมื่อพร้อมรับ */ },
      { key: 'charName',     label: 'ชื่อตัวละคร',                  placeholder: 'กรุณากรอกชื่อตัวละครในเกม',                required: true,  type: 'text' },
      { key: 'phone',        label: 'เบอร์โทรติดต่อกลับ',            placeholder: 'เบอร์โทร',                                  labelHint: 'กรณีลูกค้าต้องการให้โทรแจ้งเมื่อถึงคิว', required: false, type: 'tel' },
    ],
    packages: [
      { id: 'cod-mp-160',   amount: 160,   price: 29,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/CALLOFDUTY/COD_COIN.png' },
      { id: 'cod-mp-80',    amount: 80,    price: 33,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/CALLOFDUTY/COD_COIN.png' },
      { id: 'cod-mp-800',   amount: 800,   price: 135,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/CALLOFDUTY/COD_COIN.png' },
      { id: 'cod-mp-1600',  amount: 1600,  price: 270,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/CALLOFDUTY/COD_COIN.png' },
      { id: 'cod-mp-880',   amount: 880,   price: 280,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/CALLOFDUTY/COD_COIN.png' },
      { id: 'cod-mp-1300',  amount: 1300,  price: 415,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/CALLOFDUTY/COD_COIN.png' },
      { id: 'cod-mp-1760',  amount: 1760,  price: 560,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/CALLOFDUTY/COD_COIN.png' },
      { id: 'cod-mp-2400',  amount: 2400,  price: 650,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/CALLOFDUTY/COD_COIN.png' },
      { id: 'cod-mp-4000',  amount: 4000,  price: 660,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/CALLOFDUTY/COD_COIN.png' },
      { id: 'cod-mp-5000',  amount: 5000,  price: 1280, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/CALLOFDUTY/COD_COIN.png' },
      { id: 'cod-mp-8000',  amount: 8000,  price: 1320, badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/CALLOFDUTY/COD_COIN.png' },
      { id: 'cod-mp-7400',  amount: 7400,  price: 1930, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/CALLOFDUTY/COD_COIN.png' },
      { id: 'cod-mp-10800', amount: 10800, price: 2550, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/CALLOFDUTY/COD_COIN.png' },
      { id: 'cod-mp-16000', amount: 16000, price: 2650, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/CALLOFDUTY/COD_COIN.png' },
      { id: 'cod-mp-21600', amount: 21600, price: 5100, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/CALLOFDUTY/COD_COIN.png' },
    ],
  },

  // ══════════════════════════════════════════
  //  เกม Battle Royale
  // ══════════════════════════════════════════

  'Free Fire': {
    id: 'Free Fire',
    name: 'Free Fire',
    subtitle: 'Garena Free Fire — เติมเพชร',
    icon: '/images/GAMES ICON/FREEFIRE_iconapp.png',
    bg: '/images/GAMES BG/FREEFIRE_bg.png',
    category: 'เกม Battle Royale',
    currency: 'Diamond',
    tag: 'ขายดี',
    showOnHome: true,
    tags: [],
    accountFields: [
      { key: 'idLogin',      label: 'ID Login, Garena หรือ facebook', placeholder: 'กรุณากรอก ID Login, Garena หรือ facebook', hint: 'ไอดีที่ใช้ในการล็อคอิน เช่น Username Garena, facebook เป็นต้น', required: true,  type: 'text' },
      { key: 'password',     label: 'Password',                        placeholder: 'กรุณากรอก Password',                        hint: 'พาสเวิร์ดที่ใช้ในการล็อคอิน',                                   required: true,  type: 'password' },
      { key: 'loginChannel', label: 'ช่องทางการล็อคอินเกม',          placeholder: 'เลือก ช่องทางการล็อคอินเกม',               hint: 'ช่องทางที่ใช้ในการเข้าเกม เช่น ถ้าเข้าเกมด้วยระบบ Facebook จำเป็นต้องใช้รหัสเข้า facebook เพื่อล็อคอิน', required: true,  type: 'select',  options: ['Garena', 'Facebook'] },
      { key: 'charName',     label: 'ชื่อตัวละคร',                   placeholder: 'กรุณากรอกชื่อตัวละครในเกม',                 required: true,  type: 'text' },
      { key: 'phone',        label: 'เบอร์โทรติดต่อกลับ',             placeholder: 'เบอร์โทร',                                   labelHint: 'กรณีลูกค้าต้องการให้โทรแจ้งเมื่อถึงคิว', required: false, type: 'tel' },
    ],
    packages: [
      { id: 'ff-mp-94',    amount: 94,    price: 30,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FREEFIRE/diamond1_freefire.png' },
      { id: 'ff-mp-304',   amount: 304,   price: 85,   img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FREEFIRE/diamond1_freefire.png' },
      { id: 'ff-mp-398',   amount: 398,   price: 115,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FREEFIRE/diamond2_freefire.png' },
      { id: 'ff-mp-517',   amount: 517,   price: 139,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FREEFIRE/diamond2_freefire.png' },
      { id: 'ff-mp-611',   amount: 611,   price: 169,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FREEFIRE/diamond2_freefire.png' },
      { id: 'ff-mp-821',   amount: 821,   price: 224,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FREEFIRE/diamond3_freefire.png' },
      { id: 'ff-mp-1065',  amount: 1065,  price: 279,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FREEFIRE/diamond3_freefire.png' },
      { id: 'ff-mp-1159',  amount: 1159,  price: 309,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FREEFIRE/diamond3_freefire.png' },
      { id: 'ff-mp-1369',  amount: 1369,  price: 364,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FREEFIRE/diamond4_freefire.png' },
      { id: 'ff-mp-1582',  amount: 1582,  price: 418,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FREEFIRE/diamond4_freefire.png' },
      { id: 'ff-mp-2183',  amount: 2183,  price: 557,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FREEFIRE/diamond4_freefire.png' },
      { id: 'ff-mp-2277',  amount: 2277,  price: 587,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FREEFIRE/diamond5_freefire.png' },
      { id: 'ff-mp-2487',  amount: 2487,  price: 642,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FREEFIRE/diamond5_freefire.png' },
      { id: 'ff-mp-2700',  amount: 2700,  price: 696,  img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FREEFIRE/diamond5_freefire.png' },
      { id: 'ff-mp-3248',  amount: 3248,  price: 836,  badge: 'แนะนำ', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FREEFIRE/diamond5_freefire.png' },
      { id: 'ff-mp-4366',  amount: 4366,  price: 1114, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FREEFIRE/diamond5_freefire.png' },
      { id: 'ff-mp-5621',  amount: 5621,  price: 1380, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FREEFIRE/diamond6_freefire.png' },
      { id: 'ff-mp-7804',  amount: 7804,  price: 1937, badge: 'ขายดี', img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FREEFIRE/diamond6_freefire.png' },
      { id: 'ff-mp-11242', amount: 11242, price: 2760, img: '/images/ALASKAN_WEB_ASSET/PACKAGE%20ICON/FREEFIRE/diamond6_freefire.png' },
    ],
  },

};
